### ISSUE TITLE
Could not start the drive error upon startup

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#6] opened 2023-08-02 13:40 UTC
When I plug in my galaxy S8, I am prompted with the following message.

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/92f75cd2-9cf7-4106-bfa6-c710ea7866c5)

**Comment by GustavLindberg99** [comment] 2023-08-02 14:10
This seems to be an issue with Dokan, not AndroidDrive. The error message means that the [`DokanMain`](https://dokan-dev.github.io/dokany-doc/html/group___dokan.html#ga099fb73df80893f9da337a2dd7a6634e) function is returning [`DOKAN_START_ERROR`](https://dokan-dev.github.io/dokany-doc/html/group___dokan_main_result.html#ga3c992a2eff4303b57de60b5001d0125a). It's hard to tell from the information you provided what's causing this.

To confirm that it's an issue with Dokan, you can try running [Dokan's Mirror example](https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example) (the only thing Mirror has to do with AndroidDrive is that they both use Dokan). If you've installed Dokan (which you probably have, otherwise you would have gotten a different error message), you can run Mirror by typing the entering the following command in cmd.exe:

    "C:\Program Files\Dokan\Dokan Library-2.0.6\sample\mirror\mirror.exe" /r C:\Users /l M:\

If this works as it should, it should mount an M:\ drive with the same contents as C:\Users.

If the issue you describe is an issue with Dokan, Mirror should exit with the error message "Driver something wrong" (without mounting a drive) with about the same frequency as AndroidDrive shows the error message you describe.

If that's the case, I suggest you report an issue on [Dokan's Issues page](https://github.com/dokan-dev/dokany/issues). If you do, I recommend that you focus on Mirror rather than AndroidDrive in your bug report, since the creators of Dokan probably don't know about AndroidDrive.

**Comment by anmac1789** [comment] 2023-08-02 18:34
![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/8221d4cd-b5a0-498f-90e7-089962705655)

I just came across the directory that I had previously installed dokan. Maybe there is a conflict with the previous and newest installations. So, I'm going to uninstall all dokan libraries and install the newest version. 

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/178663f7-0cb5-4336-af62-9e89197d6a54)

I ran your command prompt command `"C:\Program Files\Dokan\Dokan Library-2.0.6\sample\mirror\mirror.exe" /r C:\Users /l M:\`

and yes, the C:\Users directory does mount as as M:\ drive.

**Comment by anmac1789** [comment] 2023-08-08 12:49
I have also tested android drive on a windows 11 x64 virtual machine on vmware and I can conclude that my galaxy s8 displays that the driver is not running error still persists.

**Comment by GustavLindberg99** [comment] 2023-08-08 13:13
That's a different error message, it means that the drive letter it's trying to assign is already taken. By default it uses D: as the drive letter, but it looks like that's already taken by the DVD drive. Normally when that happens it should choose a different drive letter automatically, I don't know why it's not doing that in your case.

Anyway, you can try choosing a different drive letter manually in Device Settings. Let me know whether that works.

**Comment by anmac1789** [comment] 2023-08-08 13:38
> That's a different error message, it means that the drive letter it's trying to assign is already taken. By default it uses D: as the drive letter, but it looks like that's already taken by the DVD drive. Normally when that happens it should choose a different drive letter automatically, I don't know why it's not doing that in your case.
> 
> Anyway, you can try choosing a different drive letter manually in Device Settings. Let me know whether that works.

The wierdest thing happened...when I chose the E:\ drive as it's drive letter, it mounted my galaxy s8 and it shows that there is 1.53 GB free of 53.2 GB but when I click inside it, it's completely empty! what the heck is going on...


![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/80694404-2460-4451-9c57-76feba93e8e4)

**Comment by GustavLindberg99** [comment] 2023-08-08 14:20
First of all, the occupied disk space displayed in This PC will not usually be equal to the size of everything in the drive. This is because the drive only shows the contents of the internal storage (which has the path `/sdcard` on Android), whereas the free and occupied disk space displayed in This PC is the total free and occupied disk space on your device, which includes not only the internal storage, but also apps and system files. Only the internal storage is actually visible in the drive, however, since seeing anything else is only possible on rooted devices, and AndroidDrive is meant to work even on non-rooted devices. So there is nothing weird with the disk space not matching the contents in itself.

However, in this case, it's weird that the drive is completely empty. Do you have anything in your internal storage? You should be able to see that by going to This PC > Galaxy S8 > Shared Internal Storage. (The Galaxy S8 icon in your screenshot corresponds to the MTP device mounted by default. Since it doesn't have a drive letter, you're very limited in what you can do with it, which is why I made AndroidDrive, but you should be able to see its contents). If it's also empty or only has files beginning with a dot, it means AndroidDrive works as expected (files beginning with a dot are hidden, you can show them by going to View > View > Hidden Files in Windows Explorer).

If you do have non-hidden files in your internal storage, there is probably a bug in AndroidDrive. If that's the case, you can try to see what the problem is by going to the folder where you installed AndroidDrive, right clicking and selecting "Open in Windows Terminal", and then running the following command:

```bash
./adb.exe shell 'stat --format=\"%F %s %W %Y %X %n\" /sdcard/* /sdcard/.* || test -d /sdcard'
```

(This command is for PowerShell, which is the default terminal for Windows Terminal. If you're using cmd.exe, you need to replace `'` with `"` and `./adb.exe` with `adb.exe`, and if you're using WSL, you need to replace `\"` with `"`).

**Comment by GustavLindberg99** [comment] 2023-08-08 14:45
Then there's a bug. Can you run the command from my last comment?

```bash
./adb.exe shell 'stat --format=\"%F %s %W %Y %X %n\" /sdcard/* /sdcard/.* || test -d /sdcard'
```

**Comment by anmac1789** [comment] 2023-08-08 15:10
> ./adb.exe shell 'stat --format=\"%F %s %W %Y %X %n\" /sdcard/* /sdcard/.* || test -d /sdcard'

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/08bd416e-8608-48c8-b6d9-928405354adb)

This is the message that I received from windows powershell terminal

**Comment by GustavLindberg99** [comment] 2023-08-08 15:12
Could you try `./adb.exe shell 'stat --help'`?

**Comment by GustavLindberg99** [comment] 2023-08-08 15:15
What's that list of options?

**Comment by anmac1789** [comment] 2023-08-08 15:17
There seems to be no %W (capital W)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/434636f6-7bdc-45b9-82b9-73cc45bb9d9b)

**Comment by GustavLindberg99** [comment] 2023-08-08 15:25
Does the following command work?

```bash
./adb.exe shell 'stat -c \"%F %s %W %Y %X %n\" /sdcard/* /sdcard/.* || test -d /sdcard'
```

**Comment by anmac1789** [comment] 2023-08-08 15:41
After running your command: `./adb.exe shell 'stat -c \"%F %s %W %Y %X %n\" /sdcard/* /sdcard/.* || test -d /sdcard'` Here is the output display

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/7acbe143-455f-421d-a955-2fd78d7b3e39)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/4ea20134-ea7d-43b4-9c6b-7a1c07db48f9)

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/271b6f11-e9f7-4205-ba52-dc77a8840862)

**Comment by anmac1789** [comment] 2023-08-08 16:18
But, I still don't see anyting in the android drive letter ....

**Comment by anmac1789** [comment] 2023-08-08 16:33
All this does it show what the format of the filename entries should be but the actual problem remains unsolved.

**Comment by anmac1789** [comment] 2023-08-08 16:46
I'm not sure what you mean by commit that referenced this issue...

**Comment by GustavLindberg99** [comment] 2023-08-08 16:55
The problem is that AndroidDrive used `stat --format`, which apparently your device doesn't support. I've changed it to `stat -c`, so this bug should be fixed in the latest version.

**Closed** 2023-08-08 16:55 UTC

**Comment by GustavLindberg99** [comment] 2023-08-12 15:56
I've figured out why you had to select a drive letter manually for it to work, even though normally AndroidDrive should select a drive letter automatically. It's because D: was already taken by the DVD drive, but since you didn't have any DVD in the DVD drive, AndroidDrive thought D: was available and tried to connect your device with that drive letter. That bug is now fixed in the latest version.

**Comment by anmac1789** [comment] 2023-08-12 16:41
> I've figured out why you had to select a drive letter manually for it to work, even though normally AndroidDrive should select a drive letter automatically. It's because D: was already taken by the DVD drive, but since you didn't have any DVD in the DVD drive, AndroidDrive thought D: was available and tried to connect your device with that drive letter. That bug is now fixed in the latest version.

I dont even have a DVD hard drive installed on my computer lol thats very strange like the hardware itself is not installed into my pc
