### ISSUE TITLE
High CPU usage when running AndroidDrive

### ISSUE THREAD

**Issue by Micccza** [GustavLindberg99/AndroidDrive#35] opened 2024-09-03 12:43 UTC
Windows 10 (latest)
CPU: 12th Gen Intel(R) Core(TM) i7-12700H   2.70 GHz

When i start AndroidDrive the CPU usage of 2 tasks goes up and my fans are runnning like wild:

1. the System task goes up to +/-4% CPU usage
2. the windows task "antimalware service executable" uses +/-10% CPU usage and the memory usage goes over 1GB...

Deactivating the windows real-time virus protection fixes no2 but now no1 goes up to +/-10% CPU usage.

Any ideas how to fix this?

btw: i already excluded the folders "C:\Program Files\AndroidDrive" and "C:\Program Files\Dokan" at the windows virus protection.

**Comment by GustavLindberg99** [comment] 2024-09-03 12:49
Duplicate of #19 (the reason why it uses a lot of CPU is the same as the reason why it's slow)

**Closed by GustavLindberg99** 2024-09-03 12:49 UTC
