### ISSUE TITLE
insufficient system resources error

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#23] opened 2023-12-07 06:45 UTC
Q: is the assigned drive letter that I choose for my pixel 7 and whenever I double-click into the Q drive, I receive the following error:

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/5bd95008-a281-4afd-8ab0-e0befe7833f1)

I notice that in task manager,

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/5cc7b9ef-7db5-4535-87e5-4a5bd54cdd28)

and also,

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/fc7b3d88-765f-4b83-951f-38ef2ae72316)

**Comment by GustavLindberg99** [comment] 2023-12-10 14:14
Duplicate of #22

**Closed by GustavLindberg99** 2023-12-10 14:14 UTC
