### ISSUE TITLE
very slow...

### ISSUE THREAD

**Issue by Matzeeee** [GustavLindberg99/AndroidDrive#32] opened 2024-08-24 10:46 UTC
Hello,
thanks for this app. It works for me with Windows 10.
But its very very slow.
So i cant not use it for sync many files....

**Comment by GustavLindberg99** [comment] 2024-08-24 10:48
Duplicate of #19

**Closed by GustavLindberg99** 2024-08-24 10:48 UTC

**Comment by Matzeeee** [comment] 2024-08-24 10:50
thanks
