### ISSUE TITLE
Corrupted files with wireless adb

### ISSUE THREAD

**Issue by palamosteliaro** [GustavLindberg99/AndroidDrive#25] opened 2024-01-19 07:22 UTC
Apologies if the program was not designed to be used with wireless adb. It seems to be connected after running the adb connect command (for the adb.exe inside the androiddrive.exe folder) and the drive mounts in windows, but all files I tried copying to and from the phone are corrupted. I can see the proper network activity while copying them, but files won't open after. Tried both small and big audio and video files.

**Comment by AJolly** [comment] 2024-02-05 16:45
Can confirm it doesnt seem to work over wireless adb. :/  I can browse the file system, but not write

**Comment by AJolly** [comment] 2024-05-21 02:12
@GustavLindberg99 any ideas about this?

**Comment by GustavLindberg99** [comment] 2024-05-26 09:03
Duplicate of #27. I've seen corrupted files even without wireless ADB at one point, but it seems to happen very rarely and it's very difficult to reproduce. I don't know if it happens more often with wireless ADB, but AndroidDrive wasn't designed for wireless ADB.

**Closed by GustavLindberg99** 2024-05-26 09:03 UTC
