### ISSUE TITLE
Slow and stalling file operations and clicks

### ISSUE THREAD

**Issue by Wayneaswell** [GustavLindberg99/AndroidDrive#28] opened 2024-04-25 15:00 UTC
Hi.  I have tried to use this to copy files, but just opening the device and folders, or context menu, operations and opening can take minutes.  Tried using teracopy but it loads a file name to the list at around a file a second out of over 10,000 and copies under 25kbytes persecond instead of 25mbytes under window explorer.  What could be wrong?

**Comment by GustavLindberg99** [comment] 2024-04-25 16:47
Duplicate of #19

**Closed by GustavLindberg99** 2024-04-25 16:47 UTC

**Comment by Wayneaswell** [comment] 2024-04-26 08:15
Not a duplicate, something is desperately wrong.  Otherwise, it would receive replies over mtp lile normal windows mtp does, hundreds of times faster, if not more.  If what was proposed was the problem, Windows mtp would also stall out on all clocks up to a minute or more.  Deleted it and working better now.  I however wonder if it is interference with the Motorola or google USB driver attempted (that helped performance and errors).  But responsiveness was not very much less before the drivers.  One other was teracopy and the Acronis, wd discovery and avast, which did not affect windows mtp.  But, it is a normal performance issue?

What was described in the other issue was many times faster.  Windows is stalling out in all clicks due to some pathway issue.
